- sqladmin/models.py
To have a consistent query  adding  **ORDER BY** before  "LIMIT" and "OFFSET"  is a must in the models list function.
:-)
solves #21
> Adding order_by to list pagination query

- sqladmin/models.py
- sqladmin/templates/detail.html
- sqladmin/templates/list.html
- tests/test_admin_async.py
- tests/test_admin_sync.py
- tests/test_models.py
Now Relationships can be used in list or detail columns:
```python
class User(Base):
__tablename__ = "users"
id = Column(Integer, primary_key=True)
name = Column(String)
email = Column(String)
birthdate = Column(Date)
addresses = relationship("Address", back_populates="user")
class Address(Base):
__tablename__ = "addresses"
id = Column(Integer, primary_key=True)
user_id = Column(Integer, ForeignKey("users.id"))
user = relationship("User", back_populates="addresses")
column_list = [User.id, User.name, User.email, User.addresses]
class AddressAdmin(ModelAdmin, model=Address):
column_list = [Address.id, Address.user]
name_plural = "Addresses"
```
Before this `User.addresses` and `Address.user` would not work with SQLAdmin.
> Allow Relationship in list and detail columns

- sqladmin/application.py
- sqladmin/models.py
- tests/test_admin_async.py
- tests/test_admin_sync.py
- tests/test_models.py
Right now all internal methods of ModelAdmin are class methods. This change will keep the same API for users but instantiate ModelAdmin internally to have normal methods instead.
> Instantiate ModelAdmin internally to avoid class methods

- sqladmin/forms.py
- sqladmin/templates/create.html
- sqladmin/templates/edit.html
This will fix the presentation in create and edit page:
Fixes #87
> Fix Boolean field checkbox UI

- README.md
Source code link was pointing to encode/starlette. Changed to current project.
> Fix Source Code Link

- docs/api_reference/model_admin.md
- sqladmin/forms.py
- sqladmin/models.py
- tests/test_forms.py
- tests/test_models.py
I added the following attributes to `ModelAdmin`:
* `form`
* `form_base_class`
* `form_args`
* `form_columns`
* `form_excluded_columns`
* `form_overrides`
All of these attributes emulate their respective functionality in the Flask-Admin API: https://flask-admin.readthedocs.io/en/latest/api/mod_model/
This PR addresses issue #96.
--
Note that I abstracted out the `get_{x}_columns()` functionality in `ModelAdmin`. Let me know if you want me to revert this back to being repetitive.
---
~~As of writing, there is one thing currently missing from my PR: the scaffolding does _not_ make use of `column_labels`. This is something I will hope to finish up soon!~~
Let me know what other changes you want me to make.
> Add form-specific functionality to ModelAdmin

- CHANGELOG.md
- docs/changelog.md
- setup.cfg
- sqladmin/__init__.py
* Add SQLModel support by @aminalaee in https://github.com/aminalaee/sqladmin/pull/94
* Add form-specific functionality to ModelAdmin by @dwreeves in https://github.com/aminalaee/sqladmin/pull/97
* Add `UUID` field converter by @aminalaee in https://github.com/aminalaee/sqladmin/pull/82
* Add PostgreSQL `INET` and `MACADDR` converters by @aminalaee in https://github.com/aminalaee/sqladmin/pull/83
* Fix Boolean field checkbox UI by @aminalaee in https://github.com/aminalaee/sqladmin/pull/88
* Fix PostgreSQL UUID PrimaryKey by @aminalaee in https://github.com/aminalaee/sqladmin/pull/92
* Fix Source Code Link by @baurt in https://github.com/aminalaee/sqladmin/pull/95
> Version 0.1.7

- docs/api_reference/model_admin.md
- requirements.txt
Long story short: fixes #104.
Locking the dependency uses mkdocstrings's so-called "experimental" handler for docstring parsing. The new one properly parses the docstring in this case whereas the legacy one does not.
> fix docstring issues by adding an explicit handler

- sqladmin/models.py
- tests/test_models.py
Fixes #118 .
Getting model attributes should work both with column names or column labels. The priority is with the column though.
> Fix get_model_attr with column labels

- sqladmin/forms.py
- This enables users who pass in `form_overrides` to bypass `self.get_converter()`, which can still break on custom/unsupported types (eg `sqlalchemy_utils.types.ChoiceType`)
> Delay call to `self.get_converter`

- CHANGELOG.md
- docs/changelog.md
- setup.cfg
- sqladmin/__init__.py
* Add csv export support by @dwreeves in https://github.com/aminalaee/sqladmin/pull/101
* Expose Starlette middlewares and debug to the Admin by @tr11 in https://github.com/aminalaee/sqladmin/pull/114
* Fix Export unlimited rows by @aminalaee in https://github.com/aminalaee/sqladmin/pull/107
* Add form and export options docs by @aminalaee in https://github.com/aminalaee/sqladmin/pull/110
* fix docstring issues by adding an explicit handler by @dwreeves in https://github.com/aminalaee/sqladmin/pull/106
* Fix get_model_attr with column labels by @aminalaee in https://github.com/aminalaee/sqladmin/pull/128
* Delay call to `self.get_converter` by @lovetoburnswhen in https://github.com/aminalaee/sqladmin/pull/129
* @tr11 made their first contribution in …
> Version 0.1.8

- docs/configurations.md
- sqladmin/application.py
Hi,
This tiny PR will fix : 
- 1 typo in `docs/configurations.md`
- 1 typo in `sqladmin/application.py`
Bye! :robot:
> docs: fix typos

- sqladmin/forms.py
- tests/test_forms.py
> Fix ModelConverter when impl is not callable

- sqladmin/forms.py
- tests/test_forms.py
This fixes the HTML required flag being present at all times and should not be required for some cases like Booleans or fields having default or server_default values.
Fixes #194
> Fix HTML required flag

- sqladmin/application.py
- sqladmin/helpers.py
- sqladmin/models.py
- sqladmin/templates/details.html
- sqladmin/templates/list.html
- sqladmin/utils.py
- tests/test_admin_async.py
- tests/test_admin_sync.py
- tests/test_models.py
> Fix handling of iterable fields

- sqladmin/fields.py
- sqladmin/forms.py
- tests/test_fields.py
When Enum is nullable, there should be an empty `option` available to choose from.
> Fix nullable Enum form

- sqladmin/application.py
- sqladmin/templates/details.html
- sqladmin/templates/list.html
Fix to use `zip` for iterating over the formatted values. It prevents retrieving `formatted_value` by index especially when it is `Iterable` but not `Sequence`.
Ref. #204.
> Use zip for iterating over the formatted values

- docs/api_reference/model_admin.md
- docs/configurations.md
- sqladmin/application.py
- sqladmin/forms.py
- sqladmin/helpers.py
- sqladmin/models.py
- sqladmin/templates/details.html
- sqladmin/templates/list.html
- tests/test_forms.py
Fixes #200 gives the option to include PK in create/edit forms.
Before you had to do this:
```python
form_columns = [User.id, ....]
```
Now if you don't want to edit form_columns you can do:
```python
form_include_pk = True
```
> Add form_include_pk option

- sqladmin/templates/base.html
- tests/test_application.py
`<title>` tag wasn't set propperly in `<head>` of html, so I fixed it
> Fix missing browser tab title

- sqladmin/__init__.py
- sqladmin/_queries.py
- sqladmin/_types.py
- sqladmin/application.py
- sqladmin/forms.py
- sqladmin/helpers.py
- sqladmin/models.py
- sqladmin/templates/layout.html
- tests/test_base_view.py
Adds `expose` method to be used for `BaseView` like:
```python
class CustomAdmin(BaseView):
name = "test"
icon = "fa fa-test"
@expose("/custom", methods=["GET"])
def custom(self, request: Request):
return self.templates.TemplateResponse(
"custom.html", context={"request": request}
)
@expose("/custom/report")
def custom_report(self, request: Request):
return self.templates.TemplateResponse(
"custom.html", context={"request": request}
)
```
> Add `expose` for BaseView

- setup.cfg
- sqladmin/forms.py
Required for Python 3.7 and in some rare case of a specific driver can be uninstalled. This makes sure this won't happen.
> Add typing_extensions to requirements

- sqladmin/_types.py
- sqladmin/application.py
`_types.py` 
```python
ENGINE_TYPE = Union[Session, AsyncSession]
```
to be
```
ENGINE_TYPE = Union[Engine, AsyncEngine]
```
`application.py`
```python
class Admin(BaseAdminView):
def __init__(
...
middlewares: Sequence[Middleware] = None,
...
) -> None:
```
to be
```
class Admin(BaseAdminView):
def __init__(
...
middlewares: Optional[Sequence[Middleware]] = None,
...
) -> None:
```
> fix `middlewares` and `ENGINE_TYPE` types

- sqladmin/application.py
- tests/test_application.py
Fixes #270.
In #266 middlewares used the `add_middleware` method which is not according to the docs, this should be reverted but the fix is needed anyway.
> Fix middlewares not working with options

- requirements.txt
- setup.cfg
- sqladmin/application.py
- sqladmin/authentication.py
- sqladmin/templates/base.html
- sqladmin/templates/layout.html
- sqladmin/templates/login.html
- tests/test_authentication.py
Add experimental Authentication.
> Add AuthenticationBackend

- CHANGELOG.md
- docs/changelog.md
- sqladmin/__init__.py
* Add `remote_ajax_refs` in https://github.com/aminalaee/sqladmin/pull/292
* Avoid select query with ajax_form_refs in https://github.com/aminalaee/sqladmin/pull/300
* Add docs for form_ajax_refs in https://github.com/aminalaee/sqladmin/pull/302
**Full Changelog**: https://github.com/aminalaee/sqladmin/compare/0.4.0...0.5.0
> Version 0.5.0

- mkdocs.yml
https://mkdocstrings.github.io/usage/#watch-directories
`watch` config deprecated since version 0.19. use the built-in watch feature.
> Remove watch in mkdocstrings mkdocs's config

- sqladmin/application.py
- sqladmin/models.py
- sqladmin/statics/js/main.js
- sqladmin/templates/details.html
- sqladmin/templates/list.html
- tests/test_admin_async.py
- tests/test_admin_sync.py
> Add bulk delete action

- tests/test_admin_async.py
- tests/test_admin_sync.py
- tests/test_authentication.py
Since starlette 0.21.0 the POST request now follows redirects.
> Update tests after starlette upgrade

- sqladmin/models.py
The descriptions of `ModelView.on_model_delete` and `ModelView.after_model_delete` seemed incorrect.  
I spotted these errors in the docs:
- https://aminalaee.dev/sqladmin/api_reference/model_view/#sqladmin.models.ModelView.after_model_delete
- https://aminalaee.dev/sqladmin/api_reference/model_view/#sqladmin.models.ModelView.on_model_delete
> Fix a couple of docstrings

- sqladmin/_queries.py
Bugfix: Previously incorrectly sets updates with 0 as value to None/NULL.
> Fix bug to allow nullable zero values

- CHANGELOG.md
- docs/changelog.md
- sqladmin/__init__.py
* Change AuthenticationBackend `authenticate` signature to support OAuth in https://github.com/aminalaee/sqladmin/pull/440
* Add File field in https://github.com/aminalaee/sqladmin/pull/424
* Support SQLALchemy Interval type in https://github.com/aminalaee/sqladmin/pull/438
* Fix docstrings by @linomp in https://github.com/aminalaee/sqladmin/pull/434
* Update to work with Starlette URL type in url_for by @aminalaee in https://github.com/aminalaee/sqladmin/pull/444
* Fix nullable Integers to accept zero value by @ovginkel in [#445](https://github.com/aminalaee/sqladmin/pull/445)
**Full Changelog**: https://github.com/aminalaee/sqladmin/compare/0.9.0...0.10.0
> Version 0.10.0

- .gitignore
- sqladmin/models.py
- tests/test_models.py
i exposed a bug working with model of non-int pk \
you may use models i wrote in test suite to reproduce this bug
the problem was there:
https://github.com/aminalaee/sqladmin/blob/4eccf67f43fbafac19aa7373a9994942dfcc627f/sqladmin/models.py#L738-L760
these methods use `pk_column` of the current model instead of the related one \
so that the urls generated threw an error of undefined attribute (cause related model didn't obtain field with current model pk_column name) \
or here due to unproccessable `value` if the field names matched: https://github.com/aminalaee/sqladmin/blob/4eccf67f43fbafac19aa7373a9994942dfcc627f/sqladmin/models.py#L850
> fix pk getters for related objects

- sqladmin/application.py
- tests/test_file_upload.py
> reset UploadFile seek after reading

- sqladmin/application.py
- sqladmin/models.py
Fixes https://github.com/aminalaee/sqladmin/issues/474
There are 3 areas:
- Details page
- Edit page
- Delete
In details it should respect `column_details_list` and `column_details_exclude_list`
In edit it should respect `form_columns` and `form_excluded_columns`
In delete we shouldn't do any joins.
> Fix unnecessary joins in different pages

- sqladmin/forms.py
Hi there,
It appears that SQLAlchemy 2.0 introduces a new UUID type, `sqlalchemy.sql.sqltypes.Uuid`. This is similar to `sqltypes.UUID` (typed with all caps), except that it also works with databases that don't have a native uuid type, in which case it uses `CHAR(32)`.
https://github.com/sqlalchemy/sqlalchemy/blob/rel_2_0_15/lib/sqlalchemy/sql/sqltypes.py#L3522-L3533
This seems to be the default type used when using declarative mappings with Python's `uuid.UUID` type.
> Support sqlalchemy.sql.sqltypes.Uuid

- sqladmin/models.py
- tests/test_models.py
Closes https://github.com/aminalaee/sqladmin/issues/524
For Enum columns, it's more meaningful to display the Enum name, instead of the value. For IntEnum case for example the name is more useful.
> Fix Enum in detail page

- CHANGELOG.md
- sqladmin/__init__.py
* Pass request to model view methods by @rossmacarthur in https://github.com/aminalaee/sqladmin/pull/547
* Set `sessionmaker` on `BaseAdmin` by @rossmacarthur in https://github.com/aminalaee/sqladmin/pull/542
* Allow custom properties by @aminalaee in https://github.com/aminalaee/sqladmin/pull/544
* Change signature of delete_model by @aminalaee in https://github.com/aminalaee/sqladmin/pull/550
* Support SQLAlchemy sessionmaker in Admin by @aminalaee in https://github.com/aminalaee/sqladmin/pull/565
* Fix `expose` and `action` Auth backend not called by @aminalaee in https://github.com/aminalaee/sqladmin/pull/561
**Full Changelog**: https://github.com/aminalaee/sqladmin/compare/0.13.0...0.14.0
> Version 0.14.0

- docs/cookbook/using_request_object.md
Fix docs: Cookbook > Using a request object. Post is created by author_id.
> Fix docs: Cookbook, Using a request object

- sqladmin/statics/js/main.js
No need to click Search button, automatically search data afer 1 seconds delay.
> Search in list when typing

- sqladmin/fields.py
- sqladmin/forms.py
- sqladmin/statics/js/main.js
- sqladmin/widgets.py
- tests/test_fields.py
Closes https://github.com/aminalaee/sqladmin/issues/594
> Switch to HTML time input for Time field

- pyproject.toml
- sqladmin/authentication.py
When importing `sqladmin.Admin`:
```py
from sqladmin import Admin
```
...the application imports from `.authentication`: https://github.com/aminalaee/sqladmin/blob/724b9a966262876701c24cfa051aeb663d385d48/sqladmin/application.py#L34
Which in turn calls `starlette.middleware.sessions`: https://github.com/aminalaee/sqladmin/blob/724b9a966262876701c24cfa051aeb663d385d48/sqladmin/authentication.py#L6
And in starlette package, `middleware.session` tries to import `itsdangerous`: https://github.com/encode/starlette/blob/cb6d284877cd359a21a0f31ebf8103a7b285a848/starlette/middleware/sessions.py#L5
However, this package is *not* installed automatically: it's part of the "full" deps: https://github.com/encode/starlette/blob/cb6d284877cd359a21a0f31ebf8103a7b285a848/pyproject.toml#L37
Therefore, it's …
> Fix 'itsdangerous' import error when not using Authentication Backend

- sqladmin/application.py
- sqladmin/models.py
- sqladmin/statics/js/main.js
- sqladmin/templates/details.html
- sqladmin/templates/list.html
Closes https://github.com/aminalaee/sqladmin/issues/608
> Add modal confirmation for bulk delete

- docs/api_reference/model_view.md
- sqladmin/models.py
Implementation Issue (#624)
I added request to the sort_query method. 
It would be possible to sort only by clicking on the column, but this would reduce the flexibility of customization.
> Add customized sort query signature (#624)

- sqladmin/_menu.py
Closes https://github.com/aminalaee/sqladmin/issues/630
> Fix ItemMenu sort issue

- sqladmin/application.py
When setting base_url="/" the ajax URL is broken, need to use urljoin to handle this properly.
> Fix Ajax breaking with base_url

- docs/cookbook/optimize_relationship_loading.md
I really don't understand it deeply but the original code example for `form_ajax_refs` from the cookbook does not work.
It is not documented anywhere why, I just found the answer in `tests/test_ajax.py`.
- There is no element `child` in the `Parent` class but there is a `children` relationship
- `"order_by": ("id",)` just does not work (`sqlalchemy.exc.ArgumentError: ORDER BY expression expected, got ('id',).`) but `"order_by": "id"` works
It would be also fine to add `__str__` method to the example implementation of the class `Child` to be more clear about what is used in the list.
> Fix docs: Cookbook form_ajax_refs definition

- docs/writing_custom_views.md
We should add `fa-solid` to properly render the fontawesome icon
Before:
After:
> Fix docs: icon not rendered in writing custom views

- sqladmin/_queries.py
- sqladmin/models.py
it's useful to access request on say on_model_change, primarily for session data. By accessing a session token set in AuthenticationBackend, you can easily implement multitenancy for example.
> Expose request to model events

- sqladmin/helpers.py
> Fix multiple PK model containing boolean values

- CHANGELOG.md
- sqladmin/__init__.py
* Switch to async templates by @aminalaee in https://github.com/aminalaee/sqladmin/pull/652
* Allow using related model fields in list/details page by @aminalaee in https://github.com/aminalaee/sqladmin/pull/653
* Allow sort by related model field by @aminalaee in https://github.com/aminalaee/sqladmin/pull/654
* Add search by related model field by @aminalaee in https://github.com/aminalaee/sqladmin/pull/655
* Expose request to model events by @holdmybeer1min in https://github.com/aminalaee/sqladmin/pull/660
* Allow model columns to bear the same name as reserved wtforms.BaseForm attributes by @brouberol in https://github.com/aminalaee/sqladmin/pull/658
* Change pk converter in routes by @aminalaee in https://github.com/aminalaee/sqladmin/pull/666
* Fix multiple PK model containing …
> Version 0.16.0

- sqladmin/application.py
- sqladmin/helpers.py
Fixed the exception handler to bring a template for the errors using an awaitable response to be matched with Starlette exception handler type hint:
```python
HTTPExceptionHandler = typing.Callable[
["Request", Exception], typing.Union["Response", typing.Awaitable["Response"]]
]
```
This PR solved the #693 issue.
> 🔨 Add http_exception handler to Admin class

- sqladmin/templates/create.html
- sqladmin/templates/edit.html
In the create and edit templates, error messages under all the fields. This is problematic if your model has many fields that extend beyond the bottom of the window. In that case there is no visible feedback of the error unless you happen to scroll to the bottom.
See discussion here: https://github.com/aminalaee/sqladmin/discussions/706
Move error messages to the top of form.
> Move non-field-specific errors to top of edit and create forms

- sqladmin/_menu.py
- sqladmin/templates/_macros.html
FIx:
1)It is necessary to add a check for displaying models in categories for which is_visible or is_accessible are equal to False. Because now they are displayed in any case, even if there are no rights. 
2)  if there are no models in the category for which is_visible and is_accessible are equal to True, then the category does not need to be shown.
> Fix Category not respecting is_visible and is_accessible

- sqladmin/templates/create.html
- sqladmin/templates/edit.html
Add Field.desctiption as small text to Create/Edit pages.
WTForms provide `Field.description` parameter to be used as help text placeholder and this PR makes use of that.
Model View for testing might look like:
```
class TestView(ModelView, model=TestEntity):
form_args = {
"field_id": {"description": "Additional description."}
}
```
> Add field description to Create/Edit templates

- sqladmin/templates/edit.html
Fixed an issue where buttons for creating new items were still shown even when can_create was set to False, leading to a 403 error if clicked.
> Hide save and add another button from edit.html if can_create is False

- sqladmin/application.py
- sqladmin/models.py
- sqladmin/templates/sqladmin/list.html
- tests/test_application.py
For page and Pagesize query paramter , Set the default value when it contain non integer value .
Fix issue: #751 
Page and PageSize set to default value when called as 
https:domainname/admin/address/list?page=somevalue
https:domainname/admin/address/list?page=2&pageSize=somevalue
and
when called as  
https:domainname/admin/address/list?page=num 
https:domainname/admin/address/list?pageSize=num
where num lies in  (0,-1,-2...)
here, page and pagesize take only positive integer
> Validate page and pageSize query parameters

- sqladmin/widgets.py
- tests/test_file_upload.py
Fixes https://github.com/aminalaee/sqladmin/issues/726
Added a `Currently` text similar to Django to show the current value.
Fixed the checkbox to be only shown when the field is in Edit and is Nullable.
> Fix File and Image fields checkbox and input

- CHANGELOG.md
- sqladmin/__init__.py
* Add field description to Create/Edit templates by @ngaranko in https://github.com/aminalaee/sqladmin/pull/722
* Add edit_form_query method by @lukeclimen in https://github.com/aminalaee/sqladmin/pull/745
* Validate page and pageSize query parameters by @BhuwanPandey in https://github.com/aminalaee/sqladmin/pull/752
* Hide save and add another button from edit.html if can_create is False by @MaximZemskov in https://github.com/aminalaee/sqladmin/pull/742
* Fix list page sort symbol by @aminalaee in https://github.com/aminalaee/sqladmin/pull/744
* Move template files from `templates` to `templates/sqladmin` by @hasansezertasan in https://github.com/aminalaee/sqladmin/pull/748
* Fix `form_args` default by @aminalaee in https://github.com/aminalaee/sqladmin/pull/756
* Fix getting column …
> Version 0.17.0

- docs/cookbook/optimize_relationship_loading.md
The documentation example give for the `edit_form_query` in the cookbook references an older implementation of the function. This updates the cookbook to provide a working example.
fixes #733
> Fix edit_form_query documentation example

- sqladmin/forms.py
- tests/test_forms/test_forms.py
Fixes https://github.com/aminalaee/sqladmin/issues/789
Exclude `column_property` from form fields. It is displayed properly in other places.
> Fix column_property

- sqladmin/pagination.py
- sqladmin/templates/sqladmin/list.html
- tests/test_pagination.py
fixes #781
New page is calculated as `((currentPage - 1) * pageSize // newPageSize) + 1` such that user will be taken to new page which has the first entry of currentPage visible.
> Fix page number issue when changing page size

- sqladmin/application.py
- sqladmin/templates/sqladmin/base.html
Hello everyone,
I recently started using sqladmin and I need to add a favicon.
I saw this merged PR #787 and I noticed that the same variable is used for both the logo and the favicon.
I updated the Admin definition so it accepts a `favicon_url`, and updated the base template.
Note: I followed the contribution guide, but have been unable to run the hatch commands locally. I am getting this error:
```sh
$ hatch run lint
/bin/sh: line 1: lint: command not found
```
I tried using other commands and subcommands  (`hatch run lint.check`) but I get the same result.
Edit: I see the commands were successful on github actions
> feat: use favicon_url instead of logo_url for favicon

- docs/authentication.md
the documet now uses `admin.app.router.add_route()` instead of `@admin.app.route()` to avoid DeprecationWarning.
resolves #809
> Document update to resolve DeprecationWarning from Starlette (#809)

- sqladmin/widgets.py
There is an unhandled exception in `AjaxSelect2Widget` after any exception in `model_view.insert_model`.
The error occurs when you pick something in the Ajax select box and there is an exception in the overridden `insert_model` method. Here is a part of the traceback:
```
File "/Users/diskream/Library/Caches/pypoetry/virtualenvs/aMY0E6K2-py3.12/lib/python3.12/site-packages/sqladmin/widgets.py", line 57, in __call__
data = field.loader.format(field.data)
│     │      │      │     └ <property object at 0x110181300>
│     │      │      └ <sqladmin.fields.AjaxSelectField object at 0x110903b90>
│     │      └ <function QueryAjaxModelLoader.format at 0x1101089a0>
│     └ <sqladmin.ajax.QueryAjaxModelLoader object at 0x1101a0b30>
└ <sqladmin.fields.AjaxSelectField object at 0x110903b90>
File …
```
> Bug fix: unhandled exception during AjaxSelect load

- sqladmin/ajax.py
- tests/test_ajax.py
Allow the passing of multiple columns into the order_by field of `form_ajax_refs`, and also allow the passing of a limit parameter, rather than always using the default.
This allows configurations such as 
``` python
form_ajax_refs = {
"order": {
"fields": ("country_id", "user_id", "order_date"),
"order_by": ["user_id", "order_date"],
"limit": 50,
}
}
```
> Allow multiple ajax sorts and changes to result size

- sqladmin/application.py
- sqladmin/models.py
- sqladmin/pagination.py
- tests/test_application.py
Hello,
This change was asked by a client complaining about the error when filtering and being on a high page. 
Imagine we have 200 rows to display. The `page_size` is 10, hence the maximum page we should access is 20.
Now imagine that we want to filter out some of the rows, using the `search` parameter. After the search, there are 100 rows to display only, so the new maximum page is 10.
This parameter is applied after typing, and the current page parameter does not change. If we are in a page greater than the new maximum, we will be prompted with the error             
```py
raise HTTPException(
status_code=400, detail="Invalid page or pageSize parameter"
)
```
This seems like unintended behaviour to me. In my view, trying to access a page higher than the max in this situation should not …
> fix: clamp page if it exceeds the maximum page

- sqladmin/models.py
This is a fix for issue https://github.com/aminalaee/sqladmin/issues/842
> Fix JSON export trailing comma

- docs/authentication.md
- sqladmin/application.py
- sqladmin/authentication.py
This pull request introduces the ability to return a custom response for the logout method in an authentication backend.
The current behavior is that the user simply gets redirected to the index page after the logout method is called. However, the current behavior does not allow for custom redirects, or manipulation of the response object, such as deletion of cookies (which might be used in some authentication scenarios). This PR overcomes this limitation.
I also took the opportunity to fix a couple of typos and docstring inconsistencies.
* **Updated logout behavior in `sqladmin/application.py`:** The `logout` method now checks if the `AuthenticationBackend.logout` method returns a `Response` and directly returns it if applicable. This allows custom responses during logout. This …
> Allow custom response in authentication logout

- docs/configurations.md
Quick hit to fix the configuration docs: 
* The User model didn't have the address relationship or a password field (which are referenced in the documentation)
* The syntax for including the related column was incorrect (it read "user.address.zip", which fails; it should just be "address.zip")
> docs: Added model context, fixed syntax

- docs/configurations.md
The `lookups` method requires a fourth, `run_query`, argument.
The `get_filtered_query` method requires a fourth, `model`, argument.
Also updated the docs, a minor clarification, that the above two are methods not fields.
It also looks like my editor removed some extra whitespace on save, I hope that's ok.
I'm also willing, if there's interest, to update the column filter code to add a `BaseFilter(ABC)` base class for all filters. Something to help enforce API consistency. Roughly:
```python
class BaseFilter(ABC):
"""
Base class for all filters.
All column filters should inherit this class and implement the required methods.
"""
@abstractmethod
def lookups(self, request: Request, model: Any, run_query: Callable[[Select], Any]) -> List[Tuple[str, str]]:
raise NotImplementedError …
```
> docs - update the example ColumnFilter
