- .github/workflows/test-suite.yml
- .gitignore
- scripts/coverage
- sqladmin/helpers.py
- sqladmin/models.py
- sqladmin/templates/layout.html
- tests/test_models.py
- slugify_class_name
- prettify_class_name
> Add `slugify` and `prettify` class names

- README.md
- docs/index.md
- sqladmin/models.py
- sqladmin/statics/css/main.css
- sqladmin/templates/base.html
- sqladmin/templates/detail.html
- sqladmin/templates/list.html
- tests/test_admin_sync.py
- tests/test_models.py
Adding `column_labels` to ModelAdmin:
```python
list_display = [User.id, User.name]
column_labels = {User.name: "Name"}
```
> Add `column_labels`

- setup.cfg
- sqladmin/__init__.py
Adds basic `list` and `detail` views.
> Version 0.1.0

- .github/workflows/publish.yml
Install dependencies and build steps.
> Update Publish workflow

- sqladmin/application.py
- sqladmin/models.py
- sqladmin/statics/js/main.js
- sqladmin/templates/base.html
- sqladmin/templates/detail.html
- sqladmin/templates/list.html
- sqladmin/templates/modals/delete.html
- tests/test_admin_sync.py
Add delete endpoint in:
- in list page, if `can_delete` is enabled.
- in detail page, If `can_delete` is enabled.
> Add `delete` endpoint

- .codecov.yml
- sqladmin/fields.py
- sqladmin/models.py
@aminalaee I like the Idea behind SQLAdmin, I will add some features to it in the future and I will use it in one of my projects soon, While I read the code I found some parts that could be refactored and enhanced to be better.
If you have any questions, we could discuss them!
> chore: Improve Code Style

- sqladmin/templates/layout.html
- tests/test_admin_async.py
- tests/test_admin_sync.py
Show `active` model in the sidebar.
> Show selected model in sidebar

- setup.cfg
- sqladmin/application.py
- sqladmin/fields.py
- sqladmin/forms.py
- sqladmin/models.py
- sqladmin/templates/create.html
- sqladmin/templates/list.html
- tests/test_admin_async.py
- tests/test_admin_sync.py
- tests/test_fields.py
- tests/test_forms.py
Adds create page:
- GET form
- POST form data validation and create model
> Add `create` page

- setup.cfg
- sqladmin/__init__.py
https://github.com/aminalaee/sqladmin/releases/edit/untagged-ceeed152edf9ab06702a
> Version 0.1.2

- sqladmin/application.py
- sqladmin/templates/layout.html
- tests/test_application.py
Add application title and logo_url options.
> Add title and logo options

- setup.cfg
- sqladmin/__init__.py
* Add `title` and `logo` options by @aminalaee in https://github.com/aminalaee/sqladmin/pull/20
* Adding `order_by` to list pagination query by @bigg01 in https://github.com/aminalaee/sqladmin/pull/25
* Allow Relationship properties in list and detail views by @aminalaee in https://github.com/aminalaee/sqladmin/pull/22
* @bigg01 made their first contribution in https://github.com/aminalaee/sqladmin/pull/25
**Full Changelog**: https://github.com/aminalaee/sqladmin/compare/0.1.2...0.1.3
> Version 0.1.3

- README.md
- docs/index.md
Adding related projects and inspirations for this project.
> Add related projects to docs

- sqladmin/application.py
- sqladmin/models.py
- sqladmin/pagination.py
- sqladmin/templates/list.html
- tests/test_admin_async.py
- tests/test_admin_sync.py
- tests/test_pagination.py
> Improve pagination

- docs/configurations.md
- mkdocs.yml
> Add configuration docs

- README.md
- docs/index.md
- setup.cfg
- sqladmin/__init__.py
* Allow templates to be configured in https://github.com/aminalaee/sqladmin/pull/52
* Add page size option links in https://github.com/aminalaee/sqladmin/pull/34
* Improve pagination in https://github.com/aminalaee/sqladmin/pull/36
* Instantiate ModelAdmin internally to avoid class methods in https://github.com/aminalaee/sqladmin/pull/31
**Full Changelog**: https://github.com/aminalaee/sqladmin/compare/0.1.3...0.1.4
> Version 0.1.4

- docs/api_reference/model_admin.md
- docs/configurations.md
- sqladmin/application.py
- sqladmin/fields.py
- sqladmin/models.py
- sqladmin/templates/create.html
- sqladmin/templates/edit.html
- sqladmin/templates/list.html
- tests/test_admin_async.py
- tests/test_admin_sync.py
Basic Edit view page.
Closes #24
> Edit view page

- docs/api_reference/model_admin.md
- docs/configurations.md
- sqladmin/application.py
- sqladmin/models.py
- sqladmin/statics/js/main.js
- sqladmin/templates/details.html
- sqladmin/templates/list.html
- tests/test_admin_async.py
- tests/test_admin_sync.py
Add `column_searchable_list ` like:
```python
column_searchable_list = [User.name, User.email]
```
> Add `column_searchable_list`

- setup.cfg
- sqladmin/__init__.py
* Authentication in https://github.com/aminalaee/sqladmin/pull/37
* Edit view page in https://github.com/aminalaee/sqladmin/pull/60
* Add `column_searchable_list` in https://github.com/aminalaee/sqladmin/pull/61
* Cleanup DB queries in https://github.com/aminalaee/sqladmin/pull/54
**Full Changelog**: https://github.com/aminalaee/sqladmin/compare/0.1.4...0.1.5
> Version 0.1.5

- CHANGELOG.md
- docs/changelog.md
- mkdocs.yml
Add Changelog to medics and root of project.
> Add Changelog

- sqladmin/statics/js/main.js
Bug example:
1. current page `http://127.0.0.1:8000/admin/project/list?search=%20`
2. set search field `test`
3. click Search
4. new page `http://127.0.0.1:8000/admin/project/list?search=test%20`
> Fix URL search regex

- docs/api_reference/model_admin.md
- sqladmin/application.py
- sqladmin/models.py
- sqladmin/templates/list.html
- tests/test_admin_async.py
- tests/test_admin_sync.py
For example:
```python
column_sortable_list = [User.id]
```
> Add `column_sortable_list`

- sqladmin/application.py
- sqladmin/fields.py
- sqladmin/forms.py
- tests/test_admin_async.py
- tests/test_admin_sync.py
- tests/test_forms.py
> Add JSON column converters

- CHANGELOG.md
- docs/changelog.md
- setup.cfg
- sqladmin/__init__.py
* FontAwesome6 icons in https://github.com/aminalaee/sqladmin/pull/78
* Add `column_sortable_list` in https://github.com/aminalaee/sqladmin/pull/65
* Add JSON column converters in https://github.com/aminalaee/sqladmin/pull/74
* Fix URL search regex in https://github.com/aminalaee/sqladmin/pull/67
* Fix Enum in Edit page in https://github.com/aminalaee/sqladmin/pull/71
**Full Changelog**: https://github.com/aminalaee/sqladmin/compare/0.1.5...0.1.6
> Version 0.1.6

- sqladmin/forms.py
- tests/test_forms.py
Adding PostgreSQL specific fields converters with validators.
> Add PostgreSQL `INET` and `MACADDR` converters

- sqladmin/forms.py
- sqladmin/models.py
- tests/test_models.py
> Fix PostgreSQL UUID PrimaryKey

- requirements.txt
- scripts/check
- sqladmin/forms.py
- tests/test_forms.py
- tests/test_integrations/test_sqlmodel.py
Fixes #57 Adds support for SQLModel.
> Add SQLModel support

- sqladmin/statics/js/main.js
Small improvement to the UI for searches.
https://www.youtube.com/watch?v=3b14d50Tgag
> [Feature] Press enter to search

- docs/api_reference/model_admin.md
- setup.cfg
- sqladmin/application.py
- sqladmin/helpers.py
- sqladmin/models.py
- sqladmin/templates/list.html
- tests/test_admin_async.py
- tests/test_admin_sync.py
- tests/test_helpers.py
- tests/test_models.py
I added csv export support.
For multiple export types, the GUI is ready, but the backend implementation of other types is not.
Also, I made it so `can_create = False` alters the UI and hides the create button.
Visual demo here: https://www.youtube.com/watch?v=Vk4luHsFgrQ
> [Feature] Add csv export support

- docs/api_reference/model_admin.md
- docs/configurations.md
Add form and export options docs
> Add form and export options docs

- requirements.txt
downgrade Flake8 and upgrade mkdocs
> Downgrade Flake8 to 3.9.2

- sqladmin/application.py
Adds the `middleware` and `debug` parameters as mentioned in #113.
> Expose Starlette middlewares and debug to the Admin

- sqladmin/exceptions.py
- sqladmin/forms.py
I broke out the typing/renames from #115 into a separate PR.
> Function signature typing, and renames

- CHANGELOG.md
- docs/api_reference/model_admin.md
- sqladmin/models.py
- sqladmin/templates/list.html
- tests/test_models.py
> Add column_formatters

- CHANGELOG.md
- docs/api_reference/model_admin.md
- docs/changelog.md
- sqladmin/models.py
- sqladmin/templates/details.html
- tests/test_models.py
Following #140 this PR adds column_formatters_detail for the detail page.
> Add column_formatters_detail

- sqladmin/application.py
- sqladmin/models.py
- sqladmin/templates/details.html
- sqladmin/templates/list.html
- tests/test_admin_async.py
- tests/test_admin_sync.py
Per #124 links model relationships to the details page.
> Link relationships to detail page

- sqladmin/forms.py
- tests/test_integrations/test_sqlmodel.py
> Fix SQLModel UUID type

- sqladmin/forms.py
> Allow QuerySelectField override object_list with form_args

- sqladmin/forms.py
- tests/test_forms.py
> Add support for UUIDType from sqlalchemy_utils

- sqladmin/forms.py
> Fix form fields order when specifying columns

- requirements.txt
- sqladmin/_validators.py
- sqladmin/forms.py
- tests/test_forms.py
Add sqlalchemy_utils URL, Currency and Timezone
> Add sqlalchemy_utils URL, Currency and  Timezone

- sqladmin/forms.py
- sqladmin/models.py
Add `form_widget_args` configuration.
> Add form_widget_args

- CHANGELOG.md
- docs/changelog.md
- setup.cfg
- sqladmin/__init__.py
* Add support for one-to-one relationship by @okapies in https://github.com/aminalaee/sqladmin/pull/182
* Add support for UUIDType from sqlalchemy_utils by @okapies in https://github.com/aminalaee/sqladmin/pull/183
* Add sqlalchemy_utils URL, Currency and  Timezone by @aminalaee in https://github.com/aminalaee/sqladmin/pull/185
* Add form_widget_args by @aminalaee in https://github.com/aminalaee/sqladmin/pull/188
* Add column_default_sort by @aminalaee in https://github.com/aminalaee/sqladmin/pull/191
* Fix link relationship to details page when null by @aminalaee in https://github.com/aminalaee/sqladmin/pull/174
* docs: fix typos by @pgrimaud in https://github.com/aminalaee/sqladmin/pull/161
* Allow QuerySelectField override object_list with form_args by @aminalaee in …
> Version 0.1.10

- CHANGELOG.md
- docs/changelog.md
- setup.cfg
- sqladmin/__init__.py
* Add `form_include_pk` option by @aminalaee in https://github.com/aminalaee/sqladmin/pull/207
* Fix handling of iterable fields by @okapies in https://github.com/aminalaee/sqladmin/pull/204
* Fix nullable Enum form by @aminalaee in https://github.com/aminalaee/sqladmin/pull/205
* Use zip for iterating over the formatted values by @okapies in https://github.com/aminalaee/sqladmin/pull/206
**Full Changelog**: https://github.com/aminalaee/sqladmin/compare/0.1.10...0.1.11
> Version 0.1.11

- sqladmin/models.py
- sqladmin/templates/details.html
- sqladmin/templates/list.html
> Fix lazy subuqery in list query

- sqladmin/forms.py
- tests/test_forms.py
Looks like there is no time field converter :)
> Add time field converter

- sqladmin/models.py
- sqladmin/templates/details.html
- tests/test_models.py
> Add default_formatter for booleans

- CHANGELOG.md
- docs/changelog.md
- setup.cfg
- sqladmin/__init__.py
* Add time field converter by @ischaojie in https://github.com/aminalaee/sqladmin/pull/214
* Add Edit button for "Details" page by @cuamckuu in https://github.com/aminalaee/sqladmin/pull/222
* Add column_type_formatters by @aminalaee in https://github.com/aminalaee/sqladmin/pull/239
* Fix lazy subuqery in list query by @aminalaee in https://github.com/aminalaee/sqladmin/pull/212
* Fix missing browser tab title by @cuamckuu in https://github.com/aminalaee/sqladmin/pull/229
* Remove sourceMappingURL in JS files by @aminalaee in https://github.com/aminalaee/sqladmin/pull/231
* @ischaojie made their first contribution in https://github.com/aminalaee/sqladmin/pull/214
* @cuamckuu made their first contribution in https://github.com/aminalaee/sqladmin/pull/222
**Full Changelog**: …
> Version 0.1.12

- sqladmin/exceptions.py
- sqladmin/forms.py
- sqladmin/helpers.py
- sqladmin/models.py
> Add more SQLAlchemy helper functions

- sqladmin/_queries.py
- sqladmin/application.py
- sqladmin/fields.py
- sqladmin/forms.py
- sqladmin/helpers.py
- sqladmin/models.py
- sqladmin/types.py
- tests/common.py
- tests/test_admin_async.py
- tests/test_admin_sync.py
- tests/test_fields.py
- tests/test_models.py
Refactor to prepare the remote ajax.
> Refactor select widget to use pk instead of objects

- README.md
- docs/api_reference/application.md
- docs/authentication.md
- docs/configurations.md
- docs/index.md
- sqladmin/_queries.py
- sqladmin/application.py
- sqladmin/templates/create.html
- sqladmin/templates/details.html
- sqladmin/templates/edit.html
- sqladmin/templates/layout.html
- sqladmin/templates/list.html
- tests/test_admin_async.py
- tests/test_admin_sync.py
- tests/test_base_view.py
- tests/test_models.py
Adds:
- add_view
- add_model_view
- add_base_view
But keeps previous methods with deprecation warning.
> Add add_view, add_model_view and add_base_view

- docs/api_reference/base_view.md
- docs/configurations.md
- mkdocs.yml
- sqladmin/application.py
- sqladmin/models.py
> Add BaseView docs

- CHANGELOG.md
- docs/changelog.md
- setup.cfg
- sqladmin/__init__.py
- sqladmin/application.py
- sqladmin/forms.py
* Add `list_query`, `count_query` and `search_query` options in https://github.com/aminalaee/sqladmin/pull/243
* Add `BaseView` for custom pages by @just-an-dev in https://github.com/aminalaee/sqladmin/pull/244
* Add `expose` for BaseView in https://github.com/aminalaee/sqladmin/pull/251
* Rename `ModelAdmin` to `ModelView` in https://github.com/aminalaee/sqladmin/pull/249
* @just-an-dev made their first contribution in https://github.com/aminalaee/sqladmin/pull/244
**Full Changelog**: https://github.com/aminalaee/sqladmin/compare/0.1.12...0.2.0
> Version 0.2.0

- sqladmin/application.py
- tests/test_application.py
Fixes https://github.com/aminalaee/sqladmin/issues/265
> Fix middlewares not being applied

- docs/api_reference/authentication.md
- docs/authentication.md
- mkdocs.yml
Add AuthenticationBackend docs
> Add AuthenticationBackend docs

- sqladmin/templates/login.html
> Update login form HTML fields

- CHANGELOG.md
- docs/changelog.md
- sqladmin/__init__.py
* Add `AuthenticationBackend` in [#277](https://github.com/aminalaee/sqladmin/pull/277)
* Update Authentication docs in [#278](https://github.com/aminalaee/sqladmin/pull/278)
**Full Changelog**: https://github.com/aminalaee/sqladmin/compare/0.2.1...0.3.0
> Version 0.3.0

- pyproject.toml
- tests/test_integrations/test_sqlmodel.py
Add SQLModel relationship tests
closes #247
> Add SQLModel relationship tests

- README.md
- docs/index.md
> Change Demo URL

- docs/index.md
- sqladmin/fields.py
- sqladmin/widgets.py
- tests/test_fields.py
> Remove select2 widgets

- sqladmin/fields.py
- sqladmin/forms.py
- sqladmin/statics/js/main.js
- sqladmin/widgets.py
- tests/test_fields.py
Add TimePicker based on Flatpickr
> Add TimePicker

- sqladmin/fields.py
- sqladmin/helpers.py
- sqladmin/models.py
- sqladmin/widgets.py
Remote internal function which is not useful.
> Remove as_str method

- CHANGELOG.md
- docs/changelog.md
- sqladmin/__init__.py
* Add Date and DateTime pickers using Fatpickr in https://github.com/aminalaee/sqladmin/pull/288
* Add Time picker using Flatpickr in https://github.com/aminalaee/sqladmin/pull/294
* Remove MomentJS in https://github.com/aminalaee/sqladmin/pull/289
* Remove Select2 widgets in https://github.com/aminalaee/sqladmin/pull/293
**Full Changelog**: https://github.com/aminalaee/sqladmin/compare/0.3.0...0.4.0
> Version 0.4.0

- sqladmin/forms.py
This PR does two things:
- When ajax_form_refs is available we don't need the extra query
- Limit select options to 100
> Avoid select query with ajax_form_refs

- sqladmin/templates/list.html
> Fix Lebel in sorting

- sqladmin/forms.py
> Switch Boolean field to select field

- sqladmin/_queries.py
- tests/test_admin_async.py
- tests/test_admin_sync.py
> Handle null values when column is nullable

- sqladmin/statics/js/main.js
- sqladmin/templates/list.html
Fixes https://github.com/aminalaee/sqladmin/issues/334
> Disable batch delete when can_delete=False

- sqladmin/_queries.py
- sqladmin/application.py
- sqladmin/models.py
Hello, this is my first pull request. Added a method for editing data before saving it to the database. Flask admin analog
> Add on_model_change and after_model_change methods

- sqladmin/forms.py
Closes https://github.com/aminalaee/sqladmin/issues/351
> Remove hard-coded related model limit

- sqladmin/statics/js/main.js
- sqladmin/templates/list.html
Changes:
1. Move Select items per page after pagination.
2. Ensure alignment.
3. Ensure actions along with the checkbox.
Preview:
And another piece of advice: It's better to move the actions button(view/edit/delete) to the end?
> Improve items list UI

- pyproject.toml
- sqladmin/application.py
- sqladmin/fields.py
- sqladmin/forms.py
with `no_implicit_optional` it's more clear and more readable.
> Add mypy check with config no_implicit_optional

- CHANGELOG.md
- docs/changelog.md
- sqladmin/__init__.py
* Add `on_model_change` and `after_model_change` methods by @dima23113 in https://github.com/aminalaee/sqladmin/pull/342
* Add `on_model_delete` and `after_model_delete` methods by @aminalaee in https://github.com/aminalaee/sqladmin/pull/343
* Fix search by uuid column by @aminalaee in https://github.com/aminalaee/sqladmin/pull/366
* Update tests after starlette upgrade by @aminalaee in https://github.com/aminalaee/sqladmin/pull/344
* Remove hard-coded related model limit by @aminalaee in https://github.com/aminalaee/sqladmin/pull/354
* Improve items list UI by @ischaojie in https://github.com/aminalaee/sqladmin/pull/349
* Make navbar work on small screens by @aminalaee in https://github.com/aminalaee/sqladmin/pull/362
* Add mypy check with config no_implicit_optional by @ischaojie in …
> Version 0.7.0

- sqladmin/application.py
- sqladmin/models.py
- sqladmin/templates/details.html
- sqladmin/templates/list.html
- tests/test_admin_async.py
- tests/test_admin_sync.py
- tests/test_base_view.py
- tests/test_models.py
Fixes https://github.com/aminalaee/sqladmin/issues/369
> Fix _url_for methods ignoring root_path

- tests/test_admin_async.py
- tests/test_admin_sync.py
- tests/test_ajax.py
- tests/test_application.py
- tests/test_base_view.py
Internal improvement of the tests
> Improve tests asserts

- sqladmin/_queries.py
- sqladmin/application.py
- sqladmin/models.py
- sqladmin/templates/action_buttons.html
- sqladmin/templates/create.html
- sqladmin/templates/details.html
- sqladmin/templates/edit.html
- tests/test_admin_async.py
- tests/test_admin_sync.py
- tests/test_application.py
- tests/test_authentication.py
Adds the following buttons:
- Save
- Save and continue editing
- Save and add another
> Add extra Save buttons for Create/Edit page

- pyproject.toml
- sqladmin/models.py
- tests/test_models.py
This PR addresses the issue described in https://github.com/aminalaee/sqladmin/issues/380
> Fix export to use `list_query` option

- sqladmin/application.py
- sqladmin/templates/create.html
- sqladmin/templates/edit.html
- tests/test_admin_async.py
- tests/test_admin_sync.py
Closes https://github.com/aminalaee/sqladmin/issues/350
Using Bootstrap alerts:
> Display errors in alert for create/edit page

- sqladmin/fields.py
Fixes https://github.com/aminalaee/sqladmin/issues/358
> Fix re-rendering create/edit page with existing data

- docs/api_reference/model_view.md
- docs/configurations.md
- sqladmin/forms.py
- sqladmin/models.py
- tests/common.py
- tests/test_forms.py
> Add custom form converters

- sqladmin/models.py
- tests/test_models.py
Fixes https://github.com/aminalaee/sqladmin/issues/401
> Fix exclude columns breaking order

- sqladmin/models.py
Fixes https://github.com/aminalaee/sqladmin/issues/339
> Fix control relationships in list page

- sqladmin/helpers.py
- tests/test_admin_async.py
Closes https://github.com/aminalaee/sqladmin/issues/413
> Fix asyncpg BigInt query

- sqladmin/fields.py
- sqladmin/forms.py
- sqladmin/statics/js/main.js
- sqladmin/widgets.py
- tests/test_fields.py
- tests/test_forms.py
Fixes https://github.com/aminalaee/sqladmin/issues/412
> Support PostgreSQL arrays

- CHANGELOG.md
- docs/changelog.md
- sqladmin/__init__.py
* Support PostgreSQL arrays in https://github.com/aminalaee/sqladmin/pull/414
* Add custom form converters in https://github.com/aminalaee/sqladmin/pull/399
* Add Custom Views docs in https://github.com/aminalaee/sqladmin/pull/408
* Fix re-rendering create/edit page with existing data in https://github.com/aminalaee/sqladmin/pull/385
* Fix exclude columns breaking order in https://github.com/aminalaee/sqladmin/pull/407
* Fix control relationships in list page in https://github.com/aminalaee/sqladmin/pull/409
* Fix asyncpg BigInt query in https://github.com/aminalaee/sqladmin/pull/416
**Full Changelog**: https://github.com/aminalaee/sqladmin/compare/0.8.0...0.9.0
> Version 0.9.0

- sqladmin/forms.py
- sqladmin/models.py
- tests/test_forms.py
- tests/test_integrations/test_sqlalchemy_utils.py
https://docs.sqlalchemy.org/en/14/orm/composites.html
> Support composite types

- pyproject.toml
- tests/test_integrations/test_sqlalchemy_utils.py
Add sqlalchemy_utils ArrowType tests
> Add sqlalchemy_utils ArrowType

- sqladmin/models.py
Fixes https://github.com/aminalaee/sqladmin/issues/429
> Remove unused code

- .gitignore
- pyproject.toml
- sqladmin/application.py
- sqladmin/fields.py
- sqladmin/forms.py
- sqladmin/templates/create.html
- sqladmin/templates/edit.html
- sqladmin/widgets.py
- tests/test_file_upload.py
- tests/test_view_async.py
Add FileType from https://github.com/aminalaee/sqlalchemy-fields
> Add File field

- docs/working_with_files.md
- mkdocs.yml
Closes https://github.com/aminalaee/sqladmin/issues/357
> Add FileType and ImageType docs

- sqladmin/fields.py
- sqladmin/forms.py
- sqladmin/helpers.py
- tests/test_fields.py
- tests/test_forms.py
- tests/test_helpers.py
Closes https://github.com/aminalaee/sqladmin/issues/327
> Support SQLALchemy Interval type

- docs/authentication.md
- pyproject.toml
- sqladmin/authentication.py
- tests/test_authentication.py
Closes https://github.com/aminalaee/sqladmin/issues/442
> Change AuthenticationBackend `authenticate` signature to support OAuth

- CHANGELOG.md
- docs/changelog.md
- sqladmin/__init__.py
* Fix PK getters for related objects by @timoniq in https://github.com/aminalaee/sqladmin/pull/449
* @timoniq made their first contribution in https://github.com/aminalaee/sqladmin/pull/449
**Full Changelog**: https://github.com/aminalaee/sqladmin/compare/0.10.0...0.10.1
> Version 0.10.1

- sqladmin/_queries.py
- sqladmin/helpers.py
- tests/test_helpers.py
Replaces https://github.com/aminalaee/sqladmin/pull/464
> Fix nullable string fields

- sqladmin/application.py
- tests/test_ajax.py
- tests/test_view_async.py
- tests/test_view_sync.py
Fixed issue where multiselect fields only select last value when creating/editing.
> Bugfix: Multiselect field saving only one value

- CHANGELOG.md
- docs/changelog.md
- sqladmin/__init__.py
* Fix nullable string fields by @aminalaee in https://github.com/aminalaee/sqladmin/pull/465
* Bugfix: Multiselect field saving only one value by @nik-joseph in https://github.com/aminalaee/sqladmin/pull/463
* Fix clear UploadFile by @aminalaee in https://github.com/aminalaee/sqladmin/pull/466
* @nik-joseph made their first contribution in https://github.com/aminalaee/sqladmin/pull/463
**Full Changelog**: https://github.com/aminalaee/sqladmin/compare/0.10.1...0.10.2
> Version 0.10.2

- CHANGELOG.md
- docs/changelog.md
- sqladmin/__init__.py
* Fix ImageType converter by @aminalaee in https://github.com/aminalaee/sqladmin/pull/471
* reset UploadFile seek after reading by @murrple-1 in https://github.com/aminalaee/sqladmin/pull/473
* Fix unnecessary joins in details and edit page by @aminalaee in https://github.com/aminalaee/sqladmin/pull/476
* @murrple-1 made their first contribution in https://github.com/aminalaee/sqladmin/pull/473
**Full Changelog**: https://github.com/aminalaee/sqladmin/compare/0.10.2...0.10.3
> Version 0.10.3

- docs/authentication.md
> Fixes a docstring typo

- CHANGELOG.md
- docs/changelog.md
- sqladmin/__init__.py
* Add ability to specify custom actions by @murrple-1 in https://github.com/aminalaee/sqladmin/pull/486
* Add `ChoiceType` by @aminalaee in https://github.com/aminalaee/sqladmin/pull/482
* Add sqlalchemy_fields URLType converter by @aminalaee in https://github.com/aminalaee/sqladmin/pull/493
* Upgrade fontawesome by @aminalaee in https://github.com/aminalaee/sqladmin/pull/481
**Full Changelog**: https://github.com/aminalaee/sqladmin/compare/0.10.3...0.11.0
> Version 0.11.0

- sqladmin/application.py
- sqladmin/models.py
- tests/test_models_action.py
> Proposal: Each ModelView can now have actions with the same name/slug

- sqladmin/models.py
- tests/test_view_async.py
- tests/test_view_sync.py
Fixes https://github.com/aminalaee/sqladmin/issues/504
> Fix count query in search page

- sqladmin/application.py
- sqladmin/authentication.py
Closes https://github.com/aminalaee/sqladmin/issues/512
> use @login_required for custom actions and views

- CHANGELOG.md
- sqladmin/__init__.py
* Support `sqlalchemy.sql.sqltypes.Uuid` by @dexter-dopping-ekco in https://github.com/aminalaee/sqladmin/pull/501
* Implement multi pk support by @dexter-dopping-ekco in https://github.com/aminalaee/sqladmin/pull/507
* Support special `__all__` keyword by @aminalaee in https://github.com/aminalaee/sqladmin/pull/511
* use @login_required for custom actions and views by @aminalaee in https://github.com/aminalaee/sqladmin/pull/513
* Each `ModelView` can now have actions with the same name/slug by @murrple-1 in https://github.com/aminalaee/sqladmin/pull/503
* Fix count query in search page by @aminalaee in https://github.com/aminalaee/sqladmin/pull/506
* @dexter-dopping-ekco made their first contribution in https://github.com/aminalaee/sqladmin/pull/501
**Full Changelog**: …
> Version 0.12.0

- pyproject.toml
removed full installation of starlette as a dependency
closes https://github.com/aminalaee/sqladmin/issues/519
> Remove httpx from requirements

- sqladmin/statics/js/main.js
> Fix issue when search query contains special characters

- pyproject.toml
- sqladmin/forms.py
- sqladmin/models.py
- tests/test_fields.py
- tests/test_integrations/test_sqlalchemy_utils.py
Closes https://github.com/aminalaee/sqladmin/issues/521
> Fix search pagination

- CHANGELOG.md
- sqladmin/__init__.py
* Remove httpx from requirements by @agn-7 in https://github.com/aminalaee/sqladmin/pull/520
* Fix issue when search query contains special characters by @uriyyo in https://github.com/aminalaee/sqladmin/pull/523
* Fix Ajax UUID by @aminalaee in https://github.com/aminalaee/sqladmin/pull/525
* Fix search pagination by @aminalaee in https://github.com/aminalaee/sqladmin/pull/528
* Drop Python3.7 by @aminalaee in https://github.com/aminalaee/sqladmin/pull/530
* Fix Enum in detail page by @aminalaee in https://github.com/aminalaee/sqladmin/pull/531
* Add `unique()` to query related models by @florianabel in https://github.com/aminalaee/sqladmin/pull/535
* Add PosrgreSQL JSONB type support by @uriyyo in https://github.com/aminalaee/sqladmin/pull/533
* @agn-7 made their first contribution in …
> Version 0.13.0

- sqladmin/application.py
This is a small change which makes it easier to access the sessionmaker if you are adding your own custom routes.
> Set `sessionmaker` on `BaseAdmin`

- sqladmin/_queries.py
- sqladmin/exceptions.py
- sqladmin/helpers.py
- sqladmin/models.py
- sqladmin/templates/details.html
- sqladmin/templates/list.html
- tests/test_models.py
Fixes https://github.com/aminalaee/sqladmin/issues/515
> Refactor to use model property as string names internally

- sqladmin/application.py
- sqladmin/models.py
> Pass request to model view methods

- sqladmin/__init__.py
- sqladmin/application.py
- sqladmin/models.py
Remove deprecated `ModelAdmin` class and `register_admin` method.
> Remove deprecated methods

- sqladmin/_queries.py
- sqladmin/application.py
- sqladmin/models.py
To be aligned with other methods:
- insert_model(request, data)
- update_model(request, pk, data)
- delete_model(request, pk)
> Change signature of delete_model

- sqladmin/application.py
- sqladmin/authentication.py
- sqladmin/models.py
Closes https://github.com/aminalaee/sqladmin/issues/556
> Fix `expose` and `action` Auth backend not called

- docs/cookbook/multiple_databases.md
- mkdocs.yml
- sqladmin/_queries.py
- sqladmin/application.py
- sqladmin/forms.py
- sqladmin/helpers.py
- sqladmin/models.py
- tests/test_ajax.py
- tests/test_file_upload.py
- tests/test_forms/test_forms.py
- tests/test_forms/test_multi_pk_forms.py
- tests/test_integrations/test_sqlalchemy_utils.py
- tests/test_integrations/test_sqlmodel.py
- tests/test_models.py
- tests/test_views/test_multi_pk_view.py
- tests/test_views/test_view_async.py
- tests/test_views/test_view_sync.py
Closes https://github.com/aminalaee/sqladmin/issues/559
You can use the `sessionmaker` to achieve this:
```py
session_maker = sessionmaker(bind=engine)
admin = Admin(app=app, session_maker=session_maker)
```
> Support SQLAlchemy sessionmaker in Admin

- CHANGELOG.md
- sqladmin/__init__.py
* Fix Detail page to not use label to get value in https://github.com/aminalaee/sqladmin/pull/570
**Full Changelog**: https://github.com/aminalaee/sqladmin/compare/0.14.0...0.14.1
> Version 0.14.1

- docs/cookbook/using_wysiwyg.md
- docs/working_with_templates.md
Closes https://github.com/aminalaee/sqladmin/issues/571
> Add docs for CKEditor

- docs/configurations.md
- sqladmin/application.py
- sqladmin/models.py
- tests/test_models.py
Breaking change to fix https://github.com/aminalaee/sqladmin/issues/609
> Change signature of `list_query` and `count_query`

- sqladmin/application.py
- sqladmin/models.py
> Fx typing of Admin session_maker

- CHANGELOG.md
- sqladmin/__init__.py
* Update AuthenticationBackend signature by @aminalaee in https://github.com/aminalaee/sqladmin/pull/581
* Change signature of `list_query` and `count_query` by @aminalaee in https://github.com/aminalaee/sqladmin/pull/610
* Search in list when typing by @anton-petrov in https://github.com/aminalaee/sqladmin/pull/592
* Add `category` config by @aminalaee in https://github.com/aminalaee/sqladmin/pull/616
* Switch to HTML time input for Time field by @aminalaee in https://github.com/aminalaee/sqladmin/pull/595
* Add modal confirmation for bulk delete by @aminalaee in https://github.com/aminalaee/sqladmin/pull/612
* Fix 'itsdangerous' import error when not using Authentication Backend by @GriceTurrble in https://github.com/aminalaee/sqladmin/pull/597
* Fix docs: Cookbook, Using a request …
> Version 0.15.0

- CHANGELOG.md
- sqladmin/__init__.py
* Avoid populating Select2 input with existing option by @Toshakins in https://github.com/aminalaee/sqladmin/pull/626
* Fix ItemMenu sort issue by @aminalaee in https://github.com/aminalaee/sqladmin/pull/631
* Add customized sort query signature (#624) by @YarLikviD in https://github.com/aminalaee/sqladmin/pull/625
* @Toshakins made their first contribution in https://github.com/aminalaee/sqladmin/pull/626
* @YarLikviD made their first contribution in https://github.com/aminalaee/sqladmin/pull/625
**Full Changelog**: https://github.com/aminalaee/sqladmin/compare/0.15.0...0.15.1
> Version 0.15.1

- docs/writing_custom_views.md
- sqladmin/application.py
- sqladmin/helpers.py
- sqladmin/models.py
- sqladmin/templating.py
- tests/test_base_view.py
- tests/test_models.py
Subset of https://github.com/aminalaee/sqladmin/issues/643
> Switch to async templates

- docs/configurations.md
- sqladmin/models.py
- sqladmin/templates/details.html
- sqladmin/templates/edit.html
- sqladmin/templates/list.html
- tests/test_models.py
- tests/test_views/test_view_async.py
- tests/test_views/test_view_sync.py
Subset of https://github.com/aminalaee/sqladmin/issues/643
> Allow using related model fields in list/details page

- sqladmin/models.py
- tests/test_models.py
Subset of https://github.com/aminalaee/sqladmin/issues/643
> Allow sort by related model field

- sqladmin/models.py
- tests/test_models.py
closes https://github.com/aminalaee/sqladmin/issues/643
> Add search by related model field

- sqladmin/application.py
- sqladmin/helpers.py
Closes https://github.com/aminalaee/sqladmin/issues/663
I think this is not an ideal solution, but it will solve this problem. Will delay this to see if better ideas come up.
> Change pk converter in routes

- CHANGELOG.md
- sqladmin/__init__.py
* Update model events docs to include request by @kostyaten in https://github.com/aminalaee/sqladmin/pull/677
* Re-add http_exception handler to Admin class by @agn-7 in https://github.com/aminalaee/sqladmin/pull/694
* Template engine environment docs update by @EnotShow in https://github.com/aminalaee/sqladmin/pull/703
* Move non-field-specific errors to top of edit and create forms by @jonocodes in https://github.com/aminalaee/sqladmin/pull/707
* Fix sort by model attribute by @aminalaee in https://github.com/aminalaee/sqladmin/pull/713
* Fix Category not respecting is_visible and is_accessible by @Neverfan1 in https://github.com/aminalaee/sqladmin/pull/698
* @kostyaten made their first contribution in https://github.com/aminalaee/sqladmin/pull/677
* @EnotShow made their first …
> Version 0.16.1

- sqladmin/_queries.py
- sqladmin/models.py
Related to https://github.com/aminalaee/sqladmin/issues/704
> Switch relationship loading to selectionload

- docs/working_with_templates.md
Elaborate on how to do the template override.
Comes from https://github.com/aminalaee/sqladmin/discussions/762
> Add more docs for overriding default tempates

- CHANGELOG.md
- sqladmin/__init__.py
* Add `form_rules`, `form_create_rules`, `form_edit_rules` by @aminalaee in https://github.com/aminalaee/sqladmin/pull/779
* Add more docs for overriding default tempates by @jonocodes in https://github.com/aminalaee/sqladmin/pull/769
* Fix edit_form_query documentation example by @lukeclimen in https://github.com/aminalaee/sqladmin/pull/777
**Full Changelog**: https://github.com/aminalaee/sqladmin/compare/0.17.0...0.18.0
> Version 0.18.0

- sqladmin/application.py
- sqladmin/models.py
- tests/test_models.py
Closes https://github.com/aminalaee/sqladmin/issues/823
> Update test for form_columns order

- CHANGELOG.md
- sqladmin/__init__.py
* add json export format. by @Vasiliy566 in https://github.com/aminalaee/sqladmin/pull/829
* clamp page if it exceeds the maximum page by @alex-lambdaloopers in https://github.com/aminalaee/sqladmin/pull/814
* @Vasiliy566 made their first contribution in https://github.com/aminalaee/sqladmin/pull/829
**Full Changelog**: https://github.com/aminalaee/sqladmin/compare/0.19.0...0.20.0
> Version 0.20.0

- sqladmin/models.py
- tests/test_views/test_view_sync.py
@aminalaee sorry for that - somehow this commit missed in previous request, require this for nested models - please release it.
> Fix export json related model

- docs/api_reference/model_view.md
- docs/configurations.md
- sqladmin/application.py
- sqladmin/models.py
> Add `category_icon`

- CONTRIBUTING.md
Not very familiar with  `hatch` but the commands in `CONTRIBUTING.md` do not match with the ones used in the github actions.
> Update hatch command in CONTRIBUTING.md

- README.md
- docs/index.md
- docs/working_with_files.md
- mkdocs.yml
- pyproject.toml
Closes https://github.com/aminalaee/sqladmin/issues/910
> Fix docs URL

- docs/writing_custom_views.md
- sqladmin/application.py
- tests/test_models.py
Didn't read the documentation very thoroughly so I tried to add the `expose` decorator to a `ModelView`. 
So here is a PR  that makes that happening. 
Thanks for bringing this library!
> ModelView @expose decorator support

- sqladmin/helpers.py
- sqladmin/models.py
- tests/test_views/test_view_async.py
- tests/test_views/test_view_sync.py
Exporting non-ASCII data get issues
~~`encoding = "utf_8_sig"` added because MS Excel requires bytes signature `"\xEF\xBB\xBF"`~~
set `encoding = "utf-8"`
> export csv/json in utf-8

- sqladmin/models.py
- tests/test_file_upload.py
- tests/test_filters.py
Fixed issue #953 pagination count issue in filtering
> Fix filters inccorect records count
